error: syntax error at or near "$2"
    at E:\FUSE\backend\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.Post (E:\FUSE\backend\src\model\modelPost.js:4:5)
    at async Object.Post (E:\FUSE\backend\src\services\servicePost.js:15:5)
    at async E:\FUSE\backend\src\routes\routerPost.js:19:26

error: syntax error at or near "$2"
    at E:\FUSE\backend\node_modules\pg-pool\index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.Post (E:\FUSE\backend\src\model\modelPost.js:4:5)
    at async Object.Post (E:\FUSE\backend\src\services\servicePost.js:15:5)
    at async E:\FUSE\backend\src\routes\routerPost.js:19:26

Error: Category Invalid 3
    at Throw (E:\FUSE\backend\src\utilities\throwError.js:2:17)
    at Object.Category (E:\FUSE\backend\src\utilities\validator.js:41:9)
    at Object.Post (E:\FUSE\backend\src\services\servicePost.js:10:15)
    at E:\FUSE\backend\src\routes\routerPost.js:19:44
    at Layer.handleRequest (E:\FUSE\backend\node_modules\router\lib\layer.js:152:17)
    at next (E:\FUSE\backend\node_modules\router\lib\route.js:157:13)
    at Route.dispatch (E:\FUSE\backend\node_modules\router\lib\route.js:117:3)
    at handle (E:\FUSE\backend\node_modules\router\index.js:435:11)
    at Layer.handleRequest (E:\FUSE\backend\node_modules\router\lib\layer.js:152:17)
    at E:\FUSE\backend\node_modules\router\index.js:295:15

Error: Category Invalid 1
    at Throw (E:\FUSE\backend\src\utilities\throwError.js:2:17)
    at Object.Category (E:\FUSE\backend\src\utilities\validator.js:41:9)
    at Object.Post (E:\FUSE\backend\src\services\servicePost.js:10:15)
    at E:\FUSE\backend\src\routes\routerPost.js:19:44
    at Layer.handleRequest (E:\FUSE\backend\node_modules\router\lib\layer.js:152:17)
    at next (E:\FUSE\backend\node_modules\router\lib\route.js:157:13)
    at Route.dispatch (E:\FUSE\backend\node_modules\router\lib\route.js:117:3)
    at handle (E:\FUSE\backend\node_modules\router\index.js:435:11)
    at Layer.handleRequest (E:\FUSE\backend\node_modules\router\lib\layer.js:152:17)
    at E:\FUSE\backend\node_modules\router\index.js:295:15

Error: Category Invalid 2
    at Throw (E:\FUSE\backend\src\utilities\throwError.js:2:17)
    at Object.Category (E:\FUSE\backend\src\utilities\validator.js:43:9)
    at Object.Post (E:\FUSE\backend\src\services\servicePost.js:10:15)
    at E:\FUSE\backend\src\routes\routerPost.js:19:44
    at Layer.handleRequest (E:\FUSE\backend\node_modules\router\lib\layer.js:152:17)
    at next (E:\FUSE\backend\node_modules\router\lib\route.js:157:13)
    at Route.dispatch (E:\FUSE\backend\node_modules\router\lib\route.js:117:3)
    at handle (E:\FUSE\backend\node_modules\router\index.js:435:11)
    at Layer.handleRequest (E:\FUSE\backend\node_modules\router\lib\layer.js:152:17)
    at E:\FUSE\backend\node_modules\router\index.js:295:15

